import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PokemonSelectionProvider } from "@/contexts/pokemonSelectionContext";
import { BattleProvider } from "@/contexts/battleContext";
import "@/styles/globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pokémon Arena",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PokemonSelectionProvider>
          <BattleProvider>
            {children}
          </BattleProvider>
        </PokemonSelectionProvider>
      </body>
    </html>
  );
}
